FROM node:20-alpine

# Install dependencies for Strapi (sharp/vips)
RUN apk add --no-cache build-base gcc autoconf automake zlib-dev libpng-dev vips-dev > /dev/null 2>&1

WORKDIR /opt/app

COPY package.json yarn.lock ./
RUN yarn config set network-timeout 600000 -g && yarn install

COPY . .

EXPOSE 1341

CMD ["yarn", "develop"]
